
package testClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestInvocationService", targetNamespace = "http://test.sca.oasisopen.org/", wsdlLocation = "file:/C:/temp/TestClient_WSDL/TestClient.wsdl")
public class TestInvocationService
    extends Service
{

    private final static URL TESTINVOCATIONSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/temp/TestClient_WSDL/TestClient.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TESTINVOCATIONSERVICE_WSDL_LOCATION = url;
    }

    public TestInvocationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestInvocationService() {
        super(TESTINVOCATIONSERVICE_WSDL_LOCATION, new QName("http://test.sca.oasisopen.org/", "TestInvocationService"));
    }

    /**
     * 
     * @return
     *     returns TestInvocation
     */
    @WebEndpoint(name = "TestInvocationPort")
    public TestInvocation getTestInvocationPort() {
        return (TestInvocation)super.getPort(new QName("http://test.sca.oasisopen.org/", "TestInvocationPort"), TestInvocation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestInvocation
     */
    @WebEndpoint(name = "TestInvocationPort")
    public TestInvocation getTestInvocationPort(WebServiceFeature... features) {
        return (TestInvocation)super.getPort(new QName("http://test.sca.oasisopen.org/", "TestInvocationPort"), TestInvocation.class, features);
    }

}
