
package testClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "TestException", targetNamespace = "http://test.sca.oasisopen.org/")
public class TestException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TestException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TestException_Exception(String message, TestException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TestException_Exception(String message, TestException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: testClient.TestException
     */
    public TestException getFaultInfo() {
        return faultInfo;
    }

}
